### ISSUE TITLE
Log Tracking

### ISSUE THREAD

**Issue by maxder** [maxder/platform#26]
#### **Log files**
- [x] Create place for collecting Tomcat LocalhostAccessLog files
- [x] Build CMD batch file
 * Append multiple LocalHostAccess files into single, new date stamped file
 * Copy new file to query and user count folders
 * Move LocalHostAccess files to archive folder

#### **Build Cleanup Macros**
- [x] Query string macro
- [x] User count macro
- [x] Figure out how to edit macros
- [x] Figure out how to copy macros from one Notepad++ to another

#### **User Count Report**
- [x] Copy Tomcat LocalhostAccessLog files to User Count folder
- [x] Notepad++
  * Strip everything except IP addresses and timestamp
  * Add delimiter between IP address and timestamp
- [x] Excel (CSV)
  * Import data to page into columns
  * Filter out unique addresses
  * Tab - Manually track count on weekly basis (volume/time period; total users to date)
  * Goal = 25% of 70K users (~17.5K users)

#### **Queries Report**
- [x] Copy Tomcat LocalhostAccessLog files to Queries folder
- [x] Notepad++
  * Leave only HTTP 200 responses
  * Strip everything except query strings and timestamp
  * Add delimiter between q=, mq= and timestamp
  * Remove + signs
- [x] Excel (CSV)
  * Import data to page into columns

**Comment by maxder** [comment]
## Merge CMD Batch File
```
@ECHO OFF
:: set context
cd M:\_logs\_raw

:: combine all log files into single one
echo Combine all log files into one?
pause
echo on
for %%f in (local*.txt) do type "%%f" >> output.txt
echo off

:: copy output to folders 
echo Copy output to data folders?
pause
echo on
copy output.txt ..\queries\queries_%date:~-4,4%%date:~-10,2%%date:~-7,2%.txt
copy output.txt ..\user_count\user_count_%date:~-4,4%%date:~-10,2%%date:~-7,2%.txt
echo off

:: cleanup
echo Archive processed files?
pause
echo on
move local*.txt M:\_logs\_raw\_archive
move output.txt output_%date:~-4,4%%date:~-10,2%%date:~-7,2%.txt
echo off

pause
exit


::Date = "Mon 04/03/2017" string
::M  o  n        0  4   /   0 3   /   2 0 1 7
::14 13	12  11   10 9   8   7 6   5   4 3 2 1
::Start count from end backward
::Year (four characters starting at four from end) = %date:~-4,4%
::Month (two characters starting at ten from end = %date:~-10,2%
::Day (two characters starting at seven from end) = %date:~-7,2%
```

**Comment by maxder** [comment]
## Notepad++ Macros
#### **Create macro**
 * Macro Menu -> Start Recording
 * Perform regex and normal replacements
 * Macro Menu -> Save Current Recorded Macro... -> give it a name

#### **Edit macro**
 * Open C:\Users\{username}\AppData\Roaming\Notepad++\shortcuts.xml
 * Look for macro title, for example:
```
        <Macro name="Clean Log for Query Strings" Ctrl="no" Alt="no" Shift="no" Key="0">
```
 * SNIP - Typical entry consisting of six lines 
```
<Action type="3" message="1700" wParam="0" lParam="0" sParam="" />
<Action type="3" message="1601" wParam="0" lParam="0" sParam=".*/favicon.*" />
<Action type="3" message="1625" wParam="0" lParam="2" sParam="" />
<Action type="3" message="1602" wParam="0" lParam="0" sParam="" />
<Action type="3" message="1702" wParam="0" lParam="768" sParam="" />
<Action type="3" message="1701" wParam="0" lParam="1609" sParam="" />
```
 * SNIP - Edit -> Line Operations -> Remove Empty Lines
```
<Action type="2" message="0" wParam="42055" lParam="0" sParam="" />
```
